services:
  mongo:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: tutor-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: tutor-backend
    ports:
      - "3000:3000"
    volumes:
      - ./src/backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/tutor
    depends_on:
      mongo:
        condition: service_healthy
    command: ["pnpm", "dev"]

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: tutor-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0         # para Vite
      - PORT=5173
    depends_on:
      - backend
    command: ["pnpm", "dev", "--host"]

volumes:
  mongo-data:
  backend_node_modules:
  frontend_node_modules: