version: "3.9"

services:
  backend:
    build: ./src/backend
    container_name: tutor-backend
    ports:
      - "3000:3000"
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    command: npm run dev

  frontend:
    build: ./src/frontend
    container_name: tutor-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]

  mongo:
    image: mongo:7
    container_name: tutor-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
